apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-{{ .Values.labels.env }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.labels.env }}
spec:
  replicas: {{ .Values.env.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name}}
      env: {{ .Values.labels.env }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        env: {{ .Values.labels.env }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.env.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources: {{ .ToYaml .Values.resources | nindent 12 }}
