apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-{{ .Values.labels.env }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.labels.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.Targetport }}
      protocol: TCP
      name: http
  selector:
    matchLabels:
      app: {{ .Release.Name}}
      env: {{ .Values.labels.env }}
