# Default values for myapp prod environment


replicaCount: 3

image:
  label: prod
  repository: nginx
  pullPolicy: IfNotPresent


service:
  label: prod
  name: service-prod
  type: ClusterIP
  port: 8080
  targetPort: 8080


resources: 
  limits:
    cpu: 1
    memory: 1 Gi
  requests:
    cpu: 500m
    memory: 512Mi

