# Default values for myapp prod environment


replicaCount: 3
name: prod
labels:
  env: prod
image:
  repository: nginx
  pullPolicy: IfNotPresent


service:
  name: service-prod
  labels:
    env: prod
  type: ClusterIP
  port: 8080
  targetPort: 8080


resources: 
  limits:
    cpu: 1
    memory: 1 Gi
  requests:
    cpu: 500m
    memory: 512Mi

