# values for myapp dev environment


replicaCount: 1
name: dev
labels:
  env: dev
image: 
  repository: nginx
  pullPolicy: IfNotPresent


service:
  name: service-dev
  labels:
    env: dev
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

