name: Helm Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          helm-version: 'v3.10.0'  # Specify the desired Helm version

      # Step 3: Cache Helm charts (optional but recommended for large repos)
      - name: Cache Helm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/helm
          key: helm-dependencies-${{ runner.os }}-${{ hashFiles('**/Chart.yaml') }}
          restore-keys: |
            helm-dependencies-${{ runner.os }}-
            
      # Step 5: Run helm template to render the Kubernetes manifests
      - name: Run helm templates
        run: |
          helm template myapp ./myapp -f ./myapp/values-prod.yaml  > ./prod-output.yaml
          helm template myapp ./myapp -f ./myapp/values-dev.yaml > ./dev-output.yaml
      # Step 6: Upload the rendered Kubernetes manifests as an artifact (optional)
      - name: Upload Kubernetes manifests as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-manifests
          path: ./
