name: Helm Template

on:
  push:

jobs:
  helm-template:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: configure creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::153032582529:role/githubdeploy
        aws-region: us-east-1

    - name: Verify AWS Identity
      run: aws sts get-caller-identity
      

